channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - keras-gpu==2.4.3
  - tensorflow-gpu==2.4.1
  - scikit-learn==0.24.2
  - numba==0.52.0
  - pandas==1.2.5
  - scipy==1.6.3
  - debugpy>=1.2.1
  - pyyaml>=5.3.1
  - numpy>=1.20.2
  - leidenalg>=0.8.3
  - louvain>=0.7.0
  - plotnine>=0.8.0
  - harmonypy>=0.0.5
  - scrublet>=0.2.3
  - bbknn>=1.4.1
  - kneed>=0.7.0
  - joblib>=1.0.1

  - pip
  - pip:
    - cellex>=1.2.1
    - scanpy>=1.8
